services:
  producer:
    container_name: iot.producer
    image: iot.producer
    build:
      context: ./producer
    env_file:
      - .env
    restart: always
    depends_on:
      - rabbitmq
    networks:
      iot:
  
  consumer:
    container_name: iot.consumer
    image: iot.consumer
    build:
      context: ./consumer
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - rabbitmq
      - mongo
    networks:
      iot:

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    restart: always
    networks:
      iot:

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env
    networks:
      iot:

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      iot:

networks:
  iot:
    driver: bridge