services:
  producer:
    container_name: iot.producer
    image: iot.producer
    build:
      context: ./producer
    env_file:
      - .env
    restart: always
    networks:
      iot:
          
  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - .env
    restart: always
    networks:
      iot:

networks:
  iot:
    driver: bridge